/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiAppInit;

import javax.swing.JOptionPane;

/**
 *
 * @author Mike
 */
public class loadingPage extends javax.swing.JFrame {

    /**
     * Creates new form loadingPage
     */
    public loadingPage() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loading = new javax.swing.JProgressBar();
        percent = new javax.swing.JLabel();
        load = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        loading.setBackground(new java.awt.Color(153, 153, 255));
        loading.setForeground(new java.awt.Color(51, 0, 204));
        loading.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loading.setPreferredSize(new java.awt.Dimension(146, 10));
        jPanel1.add(loading);
        loading.setBounds(-10, 410, 790, 10);

        percent.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        percent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        percent.setText("0%");
        jPanel1.add(percent);
        percent.setBounds(680, 390, 70, 20);

        load.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        load.setForeground(new java.awt.Color(255, 255, 255));
        load.setText("Loading ...");
        jPanel1.add(load);
        load.setBounds(10, 390, 390, 20);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(710, 0, 50, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 90, 760, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/building.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-360, -70, 1130, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/gradient1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        loadingPage lp = new loadingPage();
        lp.setVisible(true);
        
        try{ 
                for (int i = 0; i <= 100; i++){
                    Thread.sleep(10);
                     lp.percent.setText(i + " %");
                     
                     if(i == 10){
                         lp.load.setText("Turning On Modules. . .");
                     }
                     if(i == 20){
                         lp.load.setText("Loading Modules. . .");
                     }
                     if(i == 50){
                         lp.load.setText("Connecting to Database. . .");
                     }
                     if(i == 60){
                          lp.load.setText("Connection Successful. . .");
                     }
                     if(i == 70){
                         lp.load.setText("Launching Application. . .");
                     }
                     
                     if(i >= 100){
                         loginForm lf = new loginForm();
                         lf.setVisible(true);
                         lp.dispose();
                     }
                     
                     lp.loading.setValue(i);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel load;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel percent;
    // End of variables declaration//GEN-END:variables
}
